### ISSUE TITLE
Add option for padding

### ISSUE THREAD

**Issue by cloudlena** [yannjor/krabby#10]
It would be great to be able to specify a number of spaced for padding (e.g., on the left). This would allow having an output like (sorry, the ANSI characters don't render well here on GitHub):

```shell
$ krabby random --padding-left 8
        Clefairy
          ▄▀▄ ▄▄▄         
          ▀▀▀▀▀▀▀▀▄▄▄▄▄▄  
          ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▄ 
         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▄
        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ 
         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  
             ▀▀▀▀▀▀▀▀▀▀   
                ▀▀ 
```

instead of 

```shell
$ krabby random
Clefairy
  ▄▀▄ ▄▄▄         
  ▀▀▀▀▀▀▀▀▄▄▄▄▄▄  
  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▄ 
 ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▄
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
 ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ 
 ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  
     ▀▀▀▀▀▀▀▀▀▀   
        ▀▀ 
```

It would simply mean prefixing every output line with X amount of spaces.

**Comment by yannjor** [comment]
Hey @cloudlena, sure this would be quite easy to add. I guess padding-left makes the most sense (perhaps also top).  I can create a pr for this or if you already have a solution in mind feel free to open one too :)
