### ISSUE TITLE
Add `--shiny` flag to `random` subcommand

### ISSUE THREAD

**Issue by spietras** [yannjor/krabby#11]
`name` subcommand already has a `--shiny` flag, which makes it possible to display a shiny version of a specified Pokemon.

`random` subcommand could also have that flag so that we could get a random shiny Pokemon.

I know it's possible to achieve this by setting the shiny probability to `1` in the configuration file, but a flag would be nice too. I can imagine some use cases with that.

**Comment by yannjor** [comment]
Good idea! :)
