### ISSUE TITLE
Option to hide Pokémon's name

### ISSUE THREAD

**Issue by kalwabed** [yannjor/krabby#16]
Hi, thanks for your work. 
I have an idea, how can we hide the pokemon name? I don't see any configuration to do that. It would be nice if we had an option for that.

Thanks a lot.

**Comment by yannjor** [comment]
Hey, there is a flag called `--no-title` which hides the name :)

**Comment by kalwabed** [comment]
Oh, I see. I need to see the code directly to find it.
Thanks. I will close it now.
