### ISSUE TITLE
What is the way to get assets？

### ISSUE THREAD

**Issue by JJLibra** [yannjor/krabby#20]
Hello! I learned from your project and tried to implement something ([Pokemonc](https://github.com/JJLibra/Pokemonc)) similar in C. 
Your project has helped me a lot, I would like to ask, is the data in the assets directory in this repository obtained through pokeapi?

**Comment by yannjor** [comment]
Hey @JJLibra ! Cool project you got there ;) If you mean the JSON data then yes they are from the PokéAPI.

**Comment by JJLibra** [comment]
Got it. Thanks for your reply. I'll try to create my own assets afterwards as well. Learn from you !
