### ISSUE TITLE
Can't visualize pokemons

### ISSUE THREAD

**Issue by alexceend** [yannjor/krabby#21]
I've installed krabby but whenever I try to visualize a pokemon, there are just characters like here:

![image](https://github.com/user-attachments/assets/63e4779c-9771-45a2-9e12-e1be3270503b)

Do I need to install an external plugin to visualize the pokemons?
Im using windows 10

**Comment by yannjor** [comment]
Hey @alexceend, what terminal and shell are you using? Displaying the sprites relies on being able to render unicode characters with ANSI color codes.

**Comment by yannjor** [comment]
It works for me with the windows terminal and powershell on windows 11.

**Comment by alexceend** [comment]
Hey I tried using it on cmd terminal using Clink and a nerdfont and with normal windows powershell but it doesnt work:(
I'll try it removing the nerdfont and without clink later

**Comment by yannjor** [comment]
I think you might need to use the [newer windows terminal](https://apps.microsoft.com/detail/9n0dx20hk701?hl=en-us&gl=US).

**Comment by alexceend** [comment]
It works with the new terminal!!
Thank you!
