### ISSUE TITLE
Primal forms

### ISSUE THREAD

**Issue by nathanjace** [yannjor/krabby#24]
Running `krabby name kyogre -f primal` makes the program panic. Is this not implemented? :)

**Comment by yannjor** [comment]
Hey @nathanjace we don't have those sprites. Could definitely add them though! :)

**Comment by nathanjace** [comment]
@yannjor pokemon-colorscripts does have it! 
What could I do to help get this done? :)

**Comment by yannjor** [comment]
@nathanjace Thanks for your enthusiasm, but I went ahead and added them myself. I just generated the sprites with [Phoney badger's generator scripts](https://gitlab.com/phoneybadger/pokemon-generator-scripts), and added the forms to the pokemon JSON. If you notice any more missing forms, please let me know, or open a PR :)
